-- ===================================================================
-- Tables for modules outside this feature's test scope
--
-- Generated from Hibernate's own DDL for the current entity mappings, exported
-- offline through the application's EntityManagerFactory (T009). It mirrors the
-- schema ddl-auto creates in deployed environments, so tests run against the
-- same shape as production. Deliberately adds no constraints Hibernate does not
-- generate: a stricter test schema would let tests pass that production fails.
--
-- Out of scope for coverage (FR-002), but still required: DatabaseConfig scans every entity in com.materia.backend and ddl-auto=validate checks all of them, so no integration test can start unless these tables exist.
-- Test-only: see FINDING-003 in specs/001-backend-module-tests/research.md.
-- ===================================================================

-- Tables
create table public.purchase_orders (confirmed_delivery_date date, expected_delivery_date date, grand_total numeric(19,4), order_date date, payment_delay_days integer, received_date date, shipping_cost numeric(19,4), tax_amount numeric(19,4), total_amount numeric(19,4), assigned_at timestamp(6), created_at timestamp(6) not null, obsoleted_at timestamp(6), updated_at timestamp(6), version bigint, currency_code varchar(10), id uuid not null, requisition_id uuid, supplier_id uuid not null, incoterm varchar(20), delivery_status varchar(30) not null check (delivery_status in ('NOT_SHIPPED','SHIPPED','IN_TRANSIT','PARTIAL','DELIVERED','DELAYED')), status varchar(30) not null check (status in ('DRAFT','SUBMITTED','CONFIRMED','READY_FOR_RECEIPT','RECEIVED','IN_PROGRESS','PARTIALLY_RECEIVED','COMPLETED','CANCELLED','REJECTED')), order_code varchar(50) not null unique, supplier_code varchar(50), approved_by varchar(100), assigned_by varchar(100), assigned_to varchar(100), created_by varchar(100), obsoleted_by varchar(100), ordered_by varchar(100), requisition_code varchar(100), updated_by varchar(100), internal_notes varchar(1000), notes varchar(1000), obsoleted_reason varchar(1000), approved_by_name varchar(255), assigned_by_name varchar(255), assigned_to_name varchar(255), delivery_terms varchar(255), ordered_by_name varchar(255), payment_terms varchar(255), supplier_name varchar(255) not null, primary key (id));
create table public.purchase_order_lines (expected_delivery_date date, line_number integer, line_total numeric(19,4), quantity integer, unit_price numeric(19,4), created_at timestamp(6) not null, updated_at timestamp(6), version bigint, currency_code varchar(10), id uuid not null, material_id uuid, purchase_order_id uuid not null, requisition_line_id uuid, supplier_id uuid, unit_of_measure varchar(20), material_code varchar(50), created_by varchar(100), updated_by varchar(100), material_description varchar(1000), notes varchar(1000), material_name varchar(255), supplier_name varchar(255), primary key (id));
create table public.goods_receipts (expected_delivery_date date, has_discrepancy boolean not null, receipt_date date, total_quantity_accepted integer, total_quantity_ordered integer, total_quantity_received integer, total_quantity_rejected integer, created_at timestamp(6) not null, obsoleted_at timestamp(6), updated_at timestamp(6), version bigint, id uuid not null, status varchar(30) not null check (status in ('DRAFT','IN_PROGRESS','COMPLETED','PARTIAL','CANCELLED')), receipt_code varchar(50) not null unique, created_by varchar(100), obsoleted_by varchar(100), purchase_order_code varchar(100), purchase_order_id varchar(100) not null, received_by varchar(100) not null, supplier_id varchar(100), updated_by varchar(100), discrepancy_notes varchar(1000), notes varchar(1000), obsoleted_reason varchar(1000), received_by_name varchar(255) not null, supplier_name varchar(255), primary key (id));
create table public.goods_receipt_lines (expiry_date date, line_number integer, line_total numeric(19,4), quantity_accepted integer, quantity_ordered integer, quantity_pending integer, quantity_received integer, quantity_rejected integer, stock_after integer, stock_before integer, unit_price numeric(19,4), created_at timestamp(6) not null, updated_at timestamp(6), version bigint, currency_code varchar(10), goods_receipt_id uuid not null, id uuid not null, material_id uuid, unit_of_measure varchar(20), quality_status varchar(30) check (quality_status in ('ACCEPTED','REJECTED','UNDER_REVIEW','PARTIAL')), material_code varchar(50) not null, batch_number varchar(100), created_by varchar(100), purchase_order_line_id varchar(100), storage_location varchar(100), supplier_id varchar(100), updated_by varchar(100), notes varchar(1000), quality_notes varchar(1000), rejection_reason varchar(1000), material_name varchar(255), supplier_name varchar(255), primary key (id));
create table public.invoices (currency_code varchar(3) not null, due_date date, has_discrepancy boolean not null, invoice_date date not null, is_verified boolean not null, paid_amount numeric(19,4), payment_date date, received_date date, total_amount numeric(19,4) not null, total_amount_with_tax numeric(19,4) not null, total_tax_amount numeric(19,4) not null, created_at timestamp(6) not null, paid_at timestamp(6), updated_at timestamp(6), verification_date timestamp(6), version bigint, id uuid not null, invoice_type varchar(30) not null check (invoice_type in ('STANDARD','CREDIT_NOTE')), status varchar(30) not null check (status in ('DRAFT','SUBMITTED','VERIFIED','PAID','CANCELLED')), invoice_code varchar(50) not null unique, supplier_code varchar(50), created_by varchar(100), external_reference varchar(100), goods_receipt_code varchar(100), goods_receipt_id varchar(100), paid_by varchar(100), purchase_order_code varchar(100), purchase_order_id varchar(100), supplier_id varchar(100) not null, updated_by varchar(100), verified_by varchar(100), discrepancy_summary varchar(1000), internal_notes varchar(1000), notes varchar(1000), paid_by_name varchar(255), supplier_name varchar(255) not null, verified_by_name varchar(255), primary key (id));
create table public.invoice_lines (currency_code varchar(3) not null, has_quantity_discrepancy boolean not null, line_number integer not null, line_total numeric(19,4) not null, line_total_with_tax numeric(19,4), quantity_discrepancy integer, quantity_invoiced integer not null, quantity_ordered integer, quantity_received integer, tax_amount numeric(19,4), unit_price numeric(19,4) not null, created_at timestamp(6) not null, updated_at timestamp(6), version bigint, id uuid not null, invoice_id uuid not null, material_code varchar(50), unit_of_measure varchar(50), created_by varchar(100), goods_receipt_line_id varchar(100), purchase_order_line_id varchar(100), updated_by varchar(100), discrepancy_notes varchar(1000), notes varchar(1000), material_name varchar(255) not null, primary key (id));
create table public.payments (currency_code varchar(3) not null, paid_amount numeric(19,4), total_amount numeric(19,4) not null, confirmed_date timestamp(6), created_at timestamp(6) not null, payment_date timestamp(6), updated_at timestamp(6), version bigint, id uuid not null, status varchar(30) not null check (status in ('DRAFT','PENDING','COMPLETED','CANCELLED')), payment_code varchar(50) not null unique, payment_method varchar(50), supplier_code varchar(50), bank_reference varchar(100), created_by varchar(100), supplier_id varchar(100) not null, transaction_id varchar(100), updated_by varchar(100), internal_notes varchar(1000), notes varchar(1000), payment_receipt varchar(255), supplier_name varchar(255) not null, primary key (id));
create table public.payment_lines (amount numeric(19,4) not null, currency_code varchar(3) not null, is_paid boolean not null, line_number integer not null, paid_amount numeric(19,4), created_at timestamp(6) not null, updated_at timestamp(6), version bigint, id uuid not null, payment_id uuid not null, created_by varchar(100), invoice_code varchar(100), invoice_id varchar(100) not null, supplier_id varchar(100) not null, updated_by varchar(100), notes varchar(1000), supplier_name varchar(255), primary key (id));
create table public.return_to_vendor (resolution_date date, return_date date, created_at timestamp(6) not null, updated_at timestamp(6), version bigint, id uuid not null, credit_note_amount varchar(50), resolution_type varchar(50), return_code varchar(50) not null unique, status varchar(50), created_by varchar(100), credit_note_reference varchar(100), goods_receipt_code varchar(100), goods_receipt_id varchar(100), purchase_order_code varchar(100), purchase_order_id varchar(100), replacement_purchase_order_code varchar(100), replacement_purchase_order_reference varchar(100), supplier_code varchar(100), supplier_id varchar(100), updated_by varchar(100), supplier_name varchar(200), rejection_summary varchar(500), return_reason varchar(500), supplier_response varchar(500), internal_notes varchar(1000), notes varchar(1000), primary key (id));
create table public.return_to_vendor_lines (is_credit_note boolean, is_replaced boolean, line_number integer, quantity_already_returned integer, quantity_to_return integer, rejected_quantity integer, created_at timestamp(6) not null, updated_at timestamp(6), version bigint, id uuid not null, return_to_vendor_id uuid not null, unit_of_measure varchar(50), created_by varchar(100), goods_receipt_line_id varchar(100), material_code varchar(100), updated_by varchar(100), material_name varchar(200), defect_description varchar(500), notes varchar(500), quality_notes varchar(500), rejection_reason varchar(500), primary key (id));

-- Indexes
create index idx_po_status on public.purchase_orders (status);
create index idx_po_delivery_status on public.purchase_orders (delivery_status);
create index idx_po_supplier_id on public.purchase_orders (supplier_id);
create index idx_po_requisition_id on public.purchase_orders (requisition_id);
create index idx_po_order_date on public.purchase_orders (order_date);
create index idx_po_expected_delivery_date on public.purchase_orders (expected_delivery_date);
create index idx_pol_purchase_order_id on public.purchase_order_lines (purchase_order_id);
create index idx_pol_material_code on public.purchase_order_lines (material_code);
create index idx_pol_line_number on public.purchase_order_lines (line_number);
create index idx_gr_purchase_order_id on public.goods_receipts (purchase_order_id);
create index idx_gr_status on public.goods_receipts (status);
create index idx_gr_received_by on public.goods_receipts (received_by);
create index idx_gr_supplier_id on public.goods_receipts (supplier_id);
create index idx_gr_receipt_date on public.goods_receipts (receipt_date);
create index idx_grl_goods_receipt_id on public.goods_receipt_lines (goods_receipt_id);
create index idx_grl_purchase_order_line_id on public.goods_receipt_lines (purchase_order_line_id);
create index idx_grl_material_code on public.goods_receipt_lines (material_code);
create index idx_grl_line_number on public.goods_receipt_lines (line_number);
create index idx_invoice_status on public.invoices (status);
create index idx_invoice_supplier_id on public.invoices (supplier_id);
create index idx_invoice_po_id on public.invoices (purchase_order_id);
create index idx_invoice_date on public.invoices (invoice_date);
create index idx_payment_status on public.payments (status);
create index idx_payment_supplier_id on public.payments (supplier_id);

-- Foreign keys
alter table if exists public.purchase_order_lines add constraint FKlm5ieywqw1p1l4oxnkup8j2m6 foreign key (purchase_order_id) references public.purchase_orders;
alter table if exists public.goods_receipt_lines add constraint FK911tv4c70yqo1u58rdfa0pf5w foreign key (goods_receipt_id) references public.goods_receipts;
alter table if exists public.invoice_lines add constraint FKsgudq2lwpa9wc92a23nggah1w foreign key (invoice_id) references public.invoices;
alter table if exists public.payment_lines add constraint FK47k1b7ps3d8d4w3o61hkdqm2v foreign key (payment_id) references public.payments;
alter table if exists public.return_to_vendor_lines add constraint FKi6bx0e37gprk2cbmeu878lmc7 foreign key (return_to_vendor_id) references public.return_to_vendor;
