-- Databases whose purchase_orders table was generated by Hibernate before READY_FOR_RECEIPT and RECEIVED existed
-- kept the old status check (with IN_PROGRESS), because V20261003_01 only creates the table when it is missing.
-- Assigning an order to a receiver then fails. Replace the check with the statuses of OrderStatus.
alter table public.purchase_orders drop constraint if exists purchase_orders_status_check;
alter table public.purchase_orders add constraint purchase_orders_status_check
    check (status in ('DRAFT','SUBMITTED','CONFIRMED','READY_FOR_RECEIPT','RECEIVED',
                      'PARTIALLY_RECEIVED','COMPLETED','CANCELLED','REJECTED'));
